// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package wikitree_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WikiTreeClient is the client API for WikiTree service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WikiTreeClient interface {
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
}

type wikiTreeClient struct {
	cc grpc.ClientConnInterface
}

func NewWikiTreeClient(cc grpc.ClientConnInterface) WikiTreeClient {
	return &wikiTreeClient{cc}
}

func (c *wikiTreeClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, "/wikitree.WikiTree/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WikiTreeServer is the server API for WikiTree service.
// All implementations must embed UnimplementedWikiTreeServer
// for forward compatibility
type WikiTreeServer interface {
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	mustEmbedUnimplementedWikiTreeServer()
}

// UnimplementedWikiTreeServer must be embedded to have forward compatible implementations.
type UnimplementedWikiTreeServer struct {
}

func (UnimplementedWikiTreeServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedWikiTreeServer) mustEmbedUnimplementedWikiTreeServer() {}

// UnsafeWikiTreeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WikiTreeServer will
// result in compilation errors.
type UnsafeWikiTreeServer interface {
	mustEmbedUnimplementedWikiTreeServer()
}

func RegisterWikiTreeServer(s grpc.ServiceRegistrar, srv WikiTreeServer) {
	s.RegisterService(&WikiTree_ServiceDesc, srv)
}

func _WikiTree_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiTreeServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wikitree.WikiTree/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiTreeServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WikiTree_ServiceDesc is the grpc.ServiceDesc for WikiTree service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WikiTree_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wikitree.WikiTree",
	HandlerType: (*WikiTreeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _WikiTree_GetProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wikitree.proto",
}
