// TODO: Consider using proto3.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: wikitree.proto

package wikitree_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Action to execute. This should be left as its default value.
	Action *string `protobuf:"bytes,1,opt,name=action,def=getProfile" json:"action,omitempty"`
	// WikiTree ID or PageId
	Key *string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	// Optional comma-separated list of fields to return
	Fields *string `protobuf:"bytes,3,opt,name=fields" json:"fields,omitempty"`
	// Optional: "wiki", "html", or "both"
	BioFormat *string `protobuf:"bytes,4,opt,name=bio_format,json=bioFormat" json:"bio_format,omitempty"`
	// If 1, then requested profiles that are redirections are followed to the final profile
	ResolveRedirect *string `protobuf:"bytes,5,opt,name=resolve_redirect,json=resolveRedirect,def=1" json:"resolve_redirect,omitempty"`
}

// Default values for GetProfileRequest fields.
const (
	Default_GetProfileRequest_Action          = string("getProfile")
	Default_GetProfileRequest_ResolveRedirect = string("1")
)

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wikitree_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wikitree_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_wikitree_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return Default_GetProfileRequest_Action
}

func (x *GetProfileRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *GetProfileRequest) GetFields() string {
	if x != nil && x.Fields != nil {
		return *x.Fields
	}
	return ""
}

func (x *GetProfileRequest) GetBioFormat() string {
	if x != nil && x.BioFormat != nil {
		return *x.BioFormat
	}
	return ""
}

func (x *GetProfileRequest) GetResolveRedirect() string {
	if x != nil && x.ResolveRedirect != nil {
		return *x.ResolveRedirect
	}
	return Default_GetProfileRequest_ResolveRedirect
}

type GetProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageName *string                     `protobuf:"bytes,1,opt,name=page_name,json=pageName" json:"page_name,omitempty"`
	Profile  *GetProfileResponse_Profile `protobuf:"bytes,2,opt,name=profile" json:"profile,omitempty"`
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wikitree_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wikitree_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_wikitree_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetPageName() string {
	if x != nil && x.PageName != nil {
		return *x.PageName
	}
	return ""
}

func (x *GetProfileResponse) GetProfile() *GetProfileResponse_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetProfileResponse_Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	PageId *int64  `protobuf:"varint,2,opt,name=page_id,json=pageId" json:"page_id,omitempty"`
	Name   *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (x *GetProfileResponse_Profile) Reset() {
	*x = GetProfileResponse_Profile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wikitree_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfileResponse_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse_Profile) ProtoMessage() {}

func (x *GetProfileResponse_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_wikitree_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse_Profile.ProtoReflect.Descriptor instead.
func (*GetProfileResponse_Profile) Descriptor() ([]byte, []int) {
	return file_wikitree_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetProfileResponse_Profile) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *GetProfileResponse_Profile) GetPageId() int64 {
	if x != nil && x.PageId != nil {
		return *x.PageId
	}
	return 0
}

func (x *GetProfileResponse_Profile) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_wikitree_proto protoreflect.FileDescriptor

var file_wikitree_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x69, 0x6b, 0x69, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x77, 0x69, 0x6b, 0x69, 0x74, 0x72, 0x65, 0x65, 0x22, 0xae, 0x01, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x3a, 0x0a, 0x67, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x69, 0x6f, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x6f, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x2c, 0x0a,
	0x10, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x5f, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x3a, 0x01, 0x31, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x22, 0xb9, 0x01, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x3e, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x77, 0x69, 0x6b, 0x69, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x1a,
	0x46, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x53, 0x0a, 0x08, 0x57, 0x69, 0x6b, 0x69, 0x54,
	0x72, 0x65, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x1b, 0x2e, 0x77, 0x69, 0x6b, 0x69, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x77, 0x69, 0x6b, 0x69, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x48, 0x5a, 0x46,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6d, 0x75, 0x73, 0x74,
	0x61, 0x72, 0x64, 0x6f, 0x2f, 0x77, 0x69, 0x6b, 0x69, 0x74, 0x72, 0x65, 0x65, 0x2d, 0x61, 0x70,
	0x69, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x77, 0x69, 0x6b, 0x69, 0x74, 0x72, 0x65,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x77, 0x69, 0x6b, 0x69, 0x74, 0x72, 0x65, 0x65,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_wikitree_proto_rawDescOnce sync.Once
	file_wikitree_proto_rawDescData = file_wikitree_proto_rawDesc
)

func file_wikitree_proto_rawDescGZIP() []byte {
	file_wikitree_proto_rawDescOnce.Do(func() {
		file_wikitree_proto_rawDescData = protoimpl.X.CompressGZIP(file_wikitree_proto_rawDescData)
	})
	return file_wikitree_proto_rawDescData
}

var file_wikitree_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wikitree_proto_goTypes = []interface{}{
	(*GetProfileRequest)(nil),          // 0: wikitree.GetProfileRequest
	(*GetProfileResponse)(nil),         // 1: wikitree.GetProfileResponse
	(*GetProfileResponse_Profile)(nil), // 2: wikitree.GetProfileResponse.Profile
}
var file_wikitree_proto_depIdxs = []int32{
	2, // 0: wikitree.GetProfileResponse.profile:type_name -> wikitree.GetProfileResponse.Profile
	0, // 1: wikitree.WikiTree.GetProfile:input_type -> wikitree.GetProfileRequest
	1, // 2: wikitree.WikiTree.GetProfile:output_type -> wikitree.GetProfileResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wikitree_proto_init() }
func file_wikitree_proto_init() {
	if File_wikitree_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wikitree_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wikitree_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wikitree_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfileResponse_Profile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wikitree_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wikitree_proto_goTypes,
		DependencyIndexes: file_wikitree_proto_depIdxs,
		MessageInfos:      file_wikitree_proto_msgTypes,
	}.Build()
	File_wikitree_proto = out.File
	file_wikitree_proto_rawDesc = nil
	file_wikitree_proto_goTypes = nil
	file_wikitree_proto_depIdxs = nil
}
